#!/bin/bash
# cat /proc/cpuinfo | grep processor | wc -l
echo "Search for: '$@'"
#[ -z "$WD" ] && export WD='.'
find $WD -type f -print0 | xargs -0 -P 8 /bin/bash -c "grep -ITH $GREP '$@' | grep -v tags | sed 's/:/ : /' | grep '$@'"

