#!/bin/bash

_pwd=`pwd`
cd ~/.vim/
git submodule init \
	&& git submodule sync --recursive \
	&& git submodule update --remote --merge --recursive \
	&& git status \
	|| echo -e "\n\n\n\n----- Cos sie jeblo...\n\n\n"

git add . \
    && git commit -m '@update '"`date +%s`, `date`" \
	&& echo "All committed!" \
	&& avatar \
    || echo "Nothing was committed..."
