#!/bin/bash

_pwd=`pwd`
cd ~/.vim/
git submodule init \
	&& git submodule sync --recursive \
	&& git submodule update --remote --merge --recursive \
	&& git status \
	&& echo "All done fine!" \
	&& avatar \
	|| echo -e "\n\n\n\n----- Cos sie jeblo...\n\n\n"
cd $_pwd
